#!/usr/bin/env node
// Reads DDD-BPM trailers from PR commits and outputs a Mermaid PR comment.
// Usage: node generate-graph.js <base-sha> <head-sha>

const { execSync } = require("child_process");

const baseSha = process.argv[2];
const headSha = process.argv[3];

if (!baseSha || !headSha) {
  console.error("Usage: generate-graph.js <base-sha> <head-sha>");
  process.exit(1);
}

// Get commits in this PR (oldest first)
let logOutput;
try {
  logOutput = execSync(`git log ${baseSha}..${headSha} --format="%H %s"`, {
    encoding: "utf8",
  });
} catch (err) {
  console.error(`git log failed: ${err.message}`);
  process.exit(1);
}

const commits = logOutput
  .trim()
  .split("\n")
  .filter(Boolean)
  .map((line) => {
    const spaceIdx = line.indexOf(" ");
    return { hash: line.slice(0, spaceIdx), subject: line.slice(spaceIdx + 1) };
  })
  .reverse();

if (commits.length === 0) {
  process.exit(0);
}

// Extract DDD-BPM trailer from each commit
const data = [];
for (const commit of commits) {
  let body;
  try {
    body = execSync(`git log -1 --format=%B ${commit.hash}`, {
      encoding: "utf8",
    });
  } catch {
    continue;
  }
  const match = body.match(/^DDD-BPM:\s*(\d+)/m);
  if (!match) continue;

  data.push({
    hash: commit.hash.slice(0, 7),
    subject: commit.subject,
    bpm: parseInt(match[1], 10),
  });
}

if (data.length === 0) {
  // No BPM trailers found — skip comment
  process.exit(0);
}

// Stats
const bpms = data.map((c) => c.bpm);
const maxBPM = Math.max(...bpms);
const avgBPM = Math.round(bpms.reduce((a, b) => a + b, 0) / bpms.length);
const deadCount = data.filter((c) => c.bpm <= 120).length;

// Mermaid xychart-beta
const threshold = 120;
const xLabels = data.map((c) => {
  const icon = c.bpm > threshold ? "OK" : "DEAD";
  return `"${c.hash}(${icon})"`;
});
const yMin = Math.max(40, Math.min(...bpms) - 20);
const yMax = Math.min(220, Math.max(...bpms) + 20);

const chart = [
  "```mermaid",
  "xychart-beta",
  `  title "Commit BPM History"`,
  `  x-axis [${xLabels.join(", ")}]`,
  `  y-axis "BPM" ${yMin} --> ${yMax}`,
  `  line [${bpms.join(", ")}]`,
  "```",
].join("\n");

const body = `## 💗 DDD Heart Rate Report

| 指標 | 値 |
|------|-----|
| 最大心拍 | ${maxBPM} bpm 🔥 |
| 平均心拍 | ${avgBPM} bpm |
| DEAD 回数 | ${deadCount} 回 💀 |

${chart}

<sub>Generated by [DDD](https://github.com/DDD-hack/DDDapp) ❤️</sub>`;

process.stdout.write(body);
