["hooks:install"]
description = "ddd-hook を使った pre-commit hook をこのリポジトリにインストールします."
run         = "dddd install-hook"

["hooks:uninstall"]
description = "pre-commit hook をアンインストールします."
run         = "dddd uninstall-hook"
